name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check json syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
